### ISSUE TITLE
update armor and weight values to match 10.26.23 update to remnant 2

### ISSUE THREAD

**Issue by ThreePixiesInATrenchcoat** [PsychicMuffin/remnant-armor-search#3]
I went through src/helpers/data.ts and changed all the armor values, using the in-game numbers without any armor-enhancing traits relic fragments or trinkets, I also fixed the resistances of dendroid leggings, which had 2 overload instead of the 2 corrosive it has in game.

github doesn't let me upload .ts files so I changed it to a .txt but here it is for your convenience, should just be a simple rename to change it back.

[data.txt](https://github.com/PsychicMuffin/remnant-armor-search/files/13195845/data.txt)

**Comment by PsychicMuffin** [comment]
oh shit, this is awesome! I saw the update and was kind of dreading going through all of it given how painstaking it was to do the first time (I didn't have all the armor in-game at the time as I hadn't beaten apoc yet, so I had to trust the wiki which was wrong on several occasions). I'll get this updated in a few minutes here, thanks a bunch!
